# Generated by Django 5.2.1 on 2025-05-16 23:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Match",
            fields=[
                ("match", models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                "db_table": "Match",
            },
        ),
        migrations.CreateModel(
            name="Player",
            fields=[
                ("player", models.BigAutoField(primary_key=True, serialize=False)),
                ("player_name", models.CharField(max_length=250)),
                ("player_position", models.CharField(max_length=250)),
                ("spike", models.BigIntegerField()),
                ("block", models.BigIntegerField()),
                ("serve", models.BigIntegerField()),
                ("set", models.BigIntegerField()),
                ("reception", models.BigIntegerField()),
                ("dig", models.BigIntegerField()),
                ("score", models.BigIntegerField()),
            ],
            options={
                "db_table": "TotalPlayerStat",
            },
        ),
        migrations.CreateModel(
            name="Season",
            fields=[
                ("season", models.BigAutoField(primary_key=True, serialize=False)),
                ("season_number", models.IntegerField(unique=True)),
                ("season_year", models.DateField()),
                ("season_gold", models.CharField(max_length=500)),
                ("season_silver", models.CharField(max_length=500)),
                ("season_bronze", models.CharField(max_length=500)),
            ],
            options={
                "db_table": "Season",
            },
        ),
        migrations.CreateModel(
            name="Tournament",
            fields=[
                ("tournament", models.BigAutoField(primary_key=True, serialize=False)),
                ("tournament_name", models.CharField(max_length=250)),
            ],
            options={
                "db_table": "Tournament",
            },
        ),
        migrations.CreateModel(
            name="PlayerPerMatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("spike", models.BigIntegerField()),
                ("block", models.BigIntegerField()),
                ("serve", models.BigIntegerField()),
                ("set", models.BigIntegerField()),
                ("reception", models.BigIntegerField()),
                ("dig", models.BigIntegerField()),
                ("score", models.BigIntegerField()),
                (
                    "match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="db_tables_app.match",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="db_tables_app.player",
                    ),
                ),
            ],
            options={
                "db_table": "PlayerPerMatch",
            },
        ),
        migrations.AddField(
            model_name="match",
            name="season",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="db_tables_app.season"
            ),
        ),
        migrations.CreateModel(
            name="Set",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("set_number", models.IntegerField()),
                ("team_a_score", models.BigIntegerField(default=0)),
                ("team_b_score", models.BigIntegerField(default=0)),
                (
                    "match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="db_tables_app.match",
                    ),
                ),
            ],
            options={
                "db_table": "Set",
            },
        ),
        migrations.CreateModel(
            name="Team",
            fields=[
                ("team", models.BigAutoField(primary_key=True, serialize=False)),
                ("team_name", models.CharField(max_length=250)),
                ("total_spike", models.BigIntegerField()),
                ("total_block", models.BigIntegerField()),
                ("total_serve", models.BigIntegerField()),
                ("total_set", models.BigIntegerField()),
                ("total_reception", models.BigIntegerField()),
                ("total_dig", models.BigIntegerField()),
                ("total_score", models.BigIntegerField()),
                ("total_errors", models.BigIntegerField()),
                (
                    "season",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="db_tables_app.season",
                    ),
                ),
            ],
            options={
                "db_table": "Team",
            },
        ),
        migrations.AddField(
            model_name="player",
            name="team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="db_tables_app.team"
            ),
        ),
        migrations.AddField(
            model_name="match",
            name="team_a",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="Matches_as_Team_a",
                to="db_tables_app.team",
            ),
        ),
        migrations.AddField(
            model_name="match",
            name="team_b",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="Matches_as_Team_b",
                to="db_tables_app.team",
            ),
        ),
        migrations.AddField(
            model_name="season",
            name="tournament",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="db_tables_app.tournament",
            ),
        ),
    ]
